-- IDS2 재시드 스크립트 (TCO403 품목별)
-- 목적: DB 초기화 이후 품목코드별 조건형 시퀀스를 2026년 기준으로 재정렬
-- 기준:
--   TABLE_NAME = 'TCO403'
--   CONDITION1 = TCO403.MATERIAL_CODE
--   CONDITION2 = '26' (yy)
--   NEXT_ID   = 300 (다음 채번 301부터 시작, 신규 INSERT 대상만 적용)

SET NOCOUNT ON;

DECLARE @TABLE_NAME NVARCHAR(30) = 'TCO403';
DECLARE @CONDITION2 NVARCHAR(50) = '26';
DECLARE @NEXT_ID DECIMAL(20, 0) = 300;

PRINT '=== IDS2 재시드 시작 ===';
PRINT 'TABLE_NAME=' + @TABLE_NAME + ', CONDITION2=' + @CONDITION2 + ', NEXT_ID=' + CONVERT(VARCHAR(30), @NEXT_ID);

-- 1) 사전 점검
SELECT
    COUNT(*) AS PRE_TOTAL_ROWS,
    SUM(CASE WHEN NEXT_ID = @NEXT_ID THEN 1 ELSE 0 END) AS PRE_MATCH_ROWS,
    SUM(CASE WHEN NEXT_ID <> @NEXT_ID THEN 1 ELSE 0 END) AS PRE_DIFF_ROWS
FROM IDS2
WHERE TABLE_NAME = @TABLE_NAME
  AND CONDITION2 = @CONDITION2;

SELECT
    COUNT(DISTINCT MATERIAL_CODE) AS TARGET_ITEM_COUNT
FROM TCO403
WHERE ISNULL(MATERIAL_CODE, '') <> '';

BEGIN TRY
    BEGIN TRANSACTION;

    ;WITH SOURCE_ITEMS AS (
        SELECT DISTINCT
            @TABLE_NAME AS TABLE_NAME,
            MATERIAL_CODE AS CONDITION1,
            @CONDITION2 AS CONDITION2,
            @NEXT_ID AS NEXT_ID
        FROM TCO403
        WHERE ISNULL(MATERIAL_CODE, '') <> ''
    )
    MERGE IDS2 WITH (HOLDLOCK) AS TARGET
    USING SOURCE_ITEMS AS SOURCE
      ON TARGET.TABLE_NAME = SOURCE.TABLE_NAME
     AND TARGET.CONDITION1 = SOURCE.CONDITION1
     AND TARGET.CONDITION2 = SOURCE.CONDITION2
    WHEN NOT MATCHED BY TARGET THEN
        INSERT (TABLE_NAME, CONDITION1, CONDITION2, NEXT_ID)
        VALUES (SOURCE.TABLE_NAME, SOURCE.CONDITION1, SOURCE.CONDITION2, SOURCE.NEXT_ID);

    COMMIT TRANSACTION;
    PRINT 'MERGE 완료 및 커밋 성공';
END TRY
BEGIN CATCH
    IF @@TRANCOUNT > 0
        ROLLBACK TRANSACTION;

    PRINT '오류로 인해 롤백됨';
    THROW;
END CATCH;

-- 2) 사후 검증: TARGET 수와 IDS2 반영 수 일치 여부
SELECT
    TARGET_CNT = (SELECT COUNT(DISTINCT MATERIAL_CODE) FROM TCO403 WHERE ISNULL(MATERIAL_CODE, '') <> ''),
    IDS2_CNT = (SELECT COUNT(*) FROM IDS2 WHERE TABLE_NAME = @TABLE_NAME AND CONDITION2 = @CONDITION2),
    DIFF_CNT = (
        SELECT COUNT(*)
        FROM IDS2
        WHERE TABLE_NAME = @TABLE_NAME
          AND CONDITION2 = @CONDITION2
          AND NEXT_ID <> @NEXT_ID
    );

-- 참고: DIFF_CNT는 기존 등록 데이터(스킵 대상)까지 포함한 값이다.

-- 3) 누락 품목 확인
SELECT T.MATERIAL_CODE AS MISSING_MATERIAL_CODE
FROM (
    SELECT DISTINCT MATERIAL_CODE
    FROM TCO403
    WHERE ISNULL(MATERIAL_CODE, '') <> ''
) T
LEFT JOIN IDS2 I
  ON I.TABLE_NAME = @TABLE_NAME
 AND I.CONDITION1 = T.MATERIAL_CODE
 AND I.CONDITION2 = @CONDITION2
WHERE I.CONDITION1 IS NULL
ORDER BY T.MATERIAL_CODE;

-- 4) 샘플 확인
SELECT TOP 20
    TABLE_NAME,
    CONDITION1,
    CONDITION2,
    NEXT_ID
FROM IDS2
WHERE TABLE_NAME = @TABLE_NAME
  AND CONDITION2 = @CONDITION2
ORDER BY CONDITION1;

PRINT '=== IDS2 재시드 종료 ===';
GO
