-- 마이그레이션: TSA308 테이블에 REQ_TYPE 컬럼 추가
-- 생성일: 2026-04-28
-- 목적: 생산의뢰 연동 시 의뢰 구분 코드/명 저장

-- TSA308 테이블에 REQ_TYPE, REQ_TYPE_NAME 컬럼 추가
IF NOT EXISTS (
    SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS 
    WHERE TABLE_NAME = 'TSA308' AND COLUMN_NAME = 'REQ_TYPE'
)
BEGIN
    ALTER TABLE TSA308 ADD REQ_TYPE VARCHAR(20);
    PRINT 'Column REQ_TYPE added to TSA308';
END
ELSE
BEGIN
    PRINT 'Column REQ_TYPE already exists in TSA308';
END

IF NOT EXISTS (
    SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS 
    WHERE TABLE_NAME = 'TSA308' AND COLUMN_NAME = 'REQ_TYPE_NAME'
)
BEGIN
    ALTER TABLE TSA308 ADD REQ_TYPE_NAME NVARCHAR(100);
    PRINT 'Column REQ_TYPE_NAME added to TSA308';
END
ELSE
BEGIN
    PRINT 'Column REQ_TYPE_NAME already exists in TSA308';
END

-- 인덱스 추가 (선택사항 - 필터 성능 개선)
IF NOT EXISTS (
    SELECT 1 FROM SYS.INDEXES 
    WHERE name = 'IDX_TSA308_REQ_TYPE' AND object_id = OBJECT_ID('TSA308')
)
BEGIN
    CREATE INDEX IDX_TSA308_REQ_TYPE ON TSA308(REQ_TYPE);
    PRINT 'Index IDX_TSA308_REQ_TYPE created';
END
