-- ================================================
-- MES 권한 관리 시스템 DDL
-- ================================================

-- 메뉴 정보 테이블
CREATE TABLE MES_MENU_INFO (
  MENU_ID varchar(20) NOT NULL,
  MENU_NM varchar(100) NOT NULL,
  MENU_DC varchar(200) DEFAULT NULL,
  PARENT_MENU_ID varchar(20) DEFAULT NULL,
  MENU_ORDR int DEFAULT 0,
  MENU_URL varchar(200) DEFAULT NULL,
  ICON_NM varchar(50) DEFAULT NULL,
  USE_AT char(1) DEFAULT 'Y',
  FRST_REGIST_PNTTM datetime DEFAULT CURRENT_TIMESTAMP,
  FRST_REGISTER_ID varchar(20) DEFAULT NULL,
  LAST_UPDT_PNTTM datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  LAST_UPDUSR_ID varchar(20) DEFAULT NULL,
  PRIMARY KEY (MENU_ID),
  KEY FK_PARENT_MENU (PARENT_MENU_ID),
  CONSTRAINT FK_PARENT_MENU FOREIGN KEY (PARENT_MENU_ID) REFERENCES MES_MENU_INFO (MENU_ID) ON DELETE CASCADE
);

-- 권한 유형 테이블
CREATE TABLE MES_PERMISSION_TYPE (
  PERMISSION_ID varchar(20) NOT NULL,
  PERMISSION_NM varchar(100) NOT NULL,
  PERMISSION_DC varchar(200) DEFAULT NULL,
  PERMISSION_LEVEL varchar(10) NOT NULL DEFAULT 'READ', -- 'read', 'write'
  USE_AT char(1) DEFAULT 'Y',
  FRST_REGIST_PNTTM datetime DEFAULT CURRENT_TIMESTAMP,
  FRST_REGISTER_ID varchar(20) DEFAULT NULL,
  LAST_UPDT_PNTTM datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  LAST_UPDUSR_ID varchar(20) DEFAULT NULL,
  PRIMARY KEY (PERMISSION_ID)
);

-- 역할 메뉴 권한 매핑 테이블
CREATE TABLE MES_ROLE_MENU_PERMISSION (
  ROLE_MENU_ID varchar(30) NOT NULL,
  GROUP_ID char(20) NOT NULL,
  MENU_ID varchar(20) NOT NULL,
  PERMISSION_ID varchar(20) NOT NULL,
  USE_AT char(1) DEFAULT 'Y',
  FRST_REGIST_PNTTM datetime DEFAULT CURRENT_TIMESTAMP,
  FRST_REGISTER_ID varchar(20) DEFAULT NULL,
  LAST_UPDT_PNTTM datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  LAST_UPDUSR_ID varchar(20) DEFAULT NULL,
  PRIMARY KEY (ROLE_MENU_ID),
  UNIQUE KEY UK_GROUP_MENU_PERMISSION (GROUP_ID, MENU_ID, PERMISSION_ID),
  KEY FK_ROLE_GROUP (GROUP_ID),
  KEY FK_ROLE_MENU (MENU_ID),
  KEY FK_ROLE_PERMISSION (PERMISSION_ID),
  CONSTRAINT FK_ROLE_GROUP FOREIGN KEY (GROUP_ID) REFERENCES LETTNAUTHORGROUPINFO (GROUP_ID) ON DELETE CASCADE,
  CONSTRAINT FK_ROLE_MENU FOREIGN KEY (MENU_ID) REFERENCES MES_MENU_INFO (MENU_ID) ON DELETE CASCADE,
  CONSTRAINT FK_ROLE_PERMISSION FOREIGN KEY (PERMISSION_ID) REFERENCES MES_PERMISSION_TYPE (PERMISSION_ID) ON DELETE CASCADE
);

-- 인덱스 추가
CREATE INDEX IDX_MENU_PARENT ON MES_MENU_INFO (PARENT_MENU_ID);
CREATE INDEX IDX_MENU_ORDER ON MES_MENU_INFO (MENU_ORDR);
CREATE INDEX IDX_PERMISSION_LEVEL ON MES_PERMISSION_TYPE (PERMISSION_LEVEL);
CREATE INDEX IDX_ROLE_MENU_GROUP ON MES_ROLE_MENU_PERMISSION (GROUP_ID);
CREATE INDEX IDX_ROLE_MENU_MENU ON MES_ROLE_MENU_PERMISSION (MENU_ID);