-- Production plan v2 migration for 1:1 TPR301M / TPR301 storage + direct-item grouping support
-- Purpose:
-- 1) keep historical plan rows compatible
-- 2) new plans store a single TPR301 row per plan
-- 3) allow UI to group direct item selections without creating extra DB rows

ALTER TABLE TPR301M
    ADD COLUMN IF NOT EXISTS ITEM_INPUT_TYPE VARCHAR(20) NOT NULL DEFAULT 'NORMAL' AFTER PRODPLAN_ID,
    ADD COLUMN IF NOT EXISTS DIRECT_GROUP_ID VARCHAR(50) NULL AFTER ITEM_INPUT_TYPE;

ALTER TABLE TPR301
    ADD COLUMN IF NOT EXISTS ITEM_INPUT_TYPE VARCHAR(20) NOT NULL DEFAULT 'NORMAL' AFTER PRODPLAN_DETAIL_ID,
    ADD COLUMN IF NOT EXISTS DIRECT_GROUP_ID VARCHAR(50) NULL AFTER ITEM_INPUT_TYPE;

CREATE INDEX IF NOT EXISTS IX_TPR301M_DIRECT_GROUP ON TPR301M (DIRECT_GROUP_ID);
CREATE INDEX IF NOT EXISTS IX_TPR301_DIRECT_GROUP ON TPR301 (DIRECT_GROUP_ID);

UPDATE TPR301M
SET ITEM_INPUT_TYPE = 'NORMAL'
WHERE ITEM_INPUT_TYPE IS NULL OR ITEM_INPUT_TYPE = '';

UPDATE TPR301
SET ITEM_INPUT_TYPE = 'NORMAL'
WHERE ITEM_INPUT_TYPE IS NULL OR ITEM_INPUT_TYPE = '';

SELECT 'Production plan v2 migration completed successfully' AS result;
