-- 생산계획 테이블 DDL (MySQL)
-- TPR301M: 생산계획 마스터
-- TPR301: 생산계획 상세
-- TPR301R: 생산계획 실적

-- 생산계획 마스터 테이블 (TPR301M)
CREATE TABLE IF NOT EXISTS TPR301M (
    FACTORY_CODE VARCHAR(10) NOT NULL DEFAULT '000001' COMMENT '회사 코드',
    PLAN_NO VARCHAR(20) NOT NULL COMMENT '계획번호',
    PLAN_DATE VARCHAR(8) NOT NULL COMMENT '계획일자 (YYYYMMDD)',
    WORKPLACE_CODE VARCHAR(20) NOT NULL COMMENT '작업장 코드',
    WORKPLACE_NAME VARCHAR(100) NULL COMMENT '작업장명',
    PLAN_STATUS VARCHAR(20) NOT NULL DEFAULT 'PLANNED' COMMENT '계획상태',
    TOTAL_PLAN_QTY DECIMAL(18,3) NOT NULL DEFAULT 0 COMMENT '총 계획수량',
    REMARK VARCHAR(500) NULL COMMENT '비고',
    USE_YN CHAR(1) NOT NULL DEFAULT 'Y' COMMENT '사용 여부',
    OPMAN_CODE VARCHAR(20) NULL COMMENT '등록자 ID',
    OPTIME DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
    OPMAN_CODE2 VARCHAR(20) NULL COMMENT '수정자 ID',
    OPTIME2 DATETIME NULL COMMENT '수정일시',
    
    PRIMARY KEY (FACTORY_CODE, PLAN_NO),
    INDEX IX_TPR301M_PLAN_DATE (PLAN_DATE),
    INDEX IX_TPR301M_WORKPLACE (WORKPLACE_CODE),
    CONSTRAINT CK_TPR301M_PLAN_STATUS CHECK (PLAN_STATUS IN ('PLANNED', 'CONFIRMED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='생산계획 마스터';

-- 생산계획 상세 테이블 (TPR301)
CREATE TABLE IF NOT EXISTS TPR301 (
    FACTORY_CODE VARCHAR(10) NOT NULL DEFAULT '000001' COMMENT '회사 코드',
    PLAN_NO VARCHAR(20) NOT NULL COMMENT '계획번호',
    PLAN_SEQ INT NOT NULL COMMENT '계획순번',
    PLAN_DATE VARCHAR(8) NOT NULL COMMENT '계획일자 (YYYYMMDD)',
    ITEM_CODE VARCHAR(50) NOT NULL COMMENT '품목코드',
    ITEM_NAME VARCHAR(200) NOT NULL COMMENT '품목명',
    PLANNED_QTY DECIMAL(18,3) NOT NULL DEFAULT 0 COMMENT '계획수량',
    ACTUAL_QTY DECIMAL(18,3) NOT NULL DEFAULT 0 COMMENT '실적수량',
    EQUIPMENT_CODE VARCHAR(20) NOT NULL COMMENT '설비코드',
    EQUIPMENT_NAME VARCHAR(100) NULL COMMENT '설비명',
    SHIFT VARCHAR(20) NULL COMMENT '근무구분',
    WORKER_CODE VARCHAR(20) NULL COMMENT '작업자 코드',
    WORKER_NAME VARCHAR(100) NULL COMMENT '작업자명',
    ORDER_NO VARCHAR(20) NULL COMMENT '생산의뢰번호',
    ORDER_SEQNO INT NULL COMMENT '생산의뢰순번',
    ORDER_HISTNO INT NULL COMMENT '생산의뢰이력번호',
    LOT_NO VARCHAR(30) NULL COMMENT 'LOT번호',
    CUSTOMER_CODE VARCHAR(20) NULL COMMENT '거래처 코드',
    CUSTOMER_NAME VARCHAR(200) NULL COMMENT '거래처명',
    REMARK VARCHAR(500) NULL COMMENT '비고',
    USE_YN CHAR(1) NOT NULL DEFAULT 'Y' COMMENT '사용 여부',
    OPMAN_CODE VARCHAR(20) NULL COMMENT '등록자 ID',
    OPTIME DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
    OPMAN_CODE2 VARCHAR(20) NULL COMMENT '수정자 ID',
    OPTIME2 DATETIME NULL COMMENT '수정일시',
    
    PRIMARY KEY (FACTORY_CODE, PLAN_NO, PLAN_SEQ),
    INDEX IX_TPR301_PLAN_DATE (PLAN_DATE),
    INDEX IX_TPR301_ITEM (ITEM_CODE),
    INDEX IX_TPR301_EQUIPMENT (EQUIPMENT_CODE),
    INDEX IX_TPR301_ORDER (ORDER_NO),
    FOREIGN KEY (FACTORY_CODE, PLAN_NO) REFERENCES TPR301M(FACTORY_CODE, PLAN_NO) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='생산계획 상세';

-- 생산계획 실적 테이블 (TPR301R)
CREATE TABLE IF NOT EXISTS TPR301R (
    FACTORY_CODE VARCHAR(10) NOT NULL DEFAULT '000001' COMMENT '회사 코드',
    PLAN_NO VARCHAR(20) NOT NULL COMMENT '계획번호',
    PLAN_SEQ INT NOT NULL COMMENT '계획순번',
    RESULT_SEQ INT NOT NULL COMMENT '실적순번',
    RESULT_DATE VARCHAR(8) NOT NULL COMMENT '실적일자 (YYYYMMDD)',
    RESULT_QTY DECIMAL(18,3) NOT NULL DEFAULT 0 COMMENT '실적수량',
    GOOD_QTY DECIMAL(18,3) NOT NULL DEFAULT 0 COMMENT '양품수량',
    BAD_QTY DECIMAL(18,3) NOT NULL DEFAULT 0 COMMENT '불량수량',
    WORKER_CODE VARCHAR(20) NULL COMMENT '작업자 코드',
    WORKER_NAME VARCHAR(100) NULL COMMENT '작업자명',
    START_TIME DATETIME NULL COMMENT '작업시작시간',
    END_TIME DATETIME NULL COMMENT '작업종료시간',
    REMARK VARCHAR(500) NULL COMMENT '비고',
    USE_YN CHAR(1) NOT NULL DEFAULT 'Y' COMMENT '사용 여부',
    OPMAN_CODE VARCHAR(20) NULL COMMENT '등록자 ID',
    OPTIME DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
    OPMAN_CODE2 VARCHAR(20) NULL COMMENT '수정자 ID',
    OPTIME2 DATETIME NULL COMMENT '수정일시',
    
    PRIMARY KEY (FACTORY_CODE, PLAN_NO, PLAN_SEQ, RESULT_SEQ),
    INDEX IX_TPR301R_RESULT_DATE (RESULT_DATE),
    INDEX IX_TPR301R_WORKER (WORKER_CODE),
    FOREIGN KEY (FACTORY_CODE, PLAN_NO, PLAN_SEQ) 
        REFERENCES TPR301(FACTORY_CODE, PLAN_NO, PLAN_SEQ) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='생산계획 실적';

-- ID 생성을 위한 테이블 데이터 추가
INSERT INTO IDS (TABLE_NAME, NEXT_ID) VALUES ('TPR301M', 1) ON DUPLICATE KEY UPDATE NEXT_ID = NEXT_ID;
INSERT INTO IDS (TABLE_NAME, NEXT_ID) VALUES ('TPR301', 1) ON DUPLICATE KEY UPDATE NEXT_ID = NEXT_ID;
INSERT INTO IDS (TABLE_NAME, NEXT_ID) VALUES ('TPR301R', 1) ON DUPLICATE KEY UPDATE NEXT_ID = NEXT_ID;

SELECT 'Production plan tables created successfully' AS result;
