-- 작업장 테이블
CREATE TABLE IF NOT EXISTS TB_WORKPLACE (
    WORKPLACE_ID VARCHAR(20) NOT NULL PRIMARY KEY COMMENT '작업장 ID',
    WORKPLACE_CODE VARCHAR(50) NOT NULL COMMENT '작업장 코드',
    WORKPLACE_NAME VARCHAR(100) NOT NULL COMMENT '작업장명',
    DESCRIPTION VARCHAR(500) COMMENT '작업장 설명',
    LOCATION VARCHAR(200) COMMENT '작업장 위치',
    WORKPLACE_TYPE VARCHAR(50) COMMENT '작업장 타입',
    STATUS VARCHAR(20) DEFAULT 'ACTIVE' COMMENT '작업장 상태 (ACTIVE/INACTIVE)',
    USE_YN CHAR(1) DEFAULT 'Y' COMMENT '사용 여부 (Y/N)',
    REG_USER_ID VARCHAR(20) COMMENT '등록자 ID',
    REG_DT DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
    UPD_USER_ID VARCHAR(20) COMMENT '수정자 ID',
    UPD_DT DATETIME COMMENT '수정일시',
    UNIQUE KEY UK_WORKPLACE_CODE (WORKPLACE_CODE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='작업장 정보';

-- 작업장별 작업자 테이블
CREATE TABLE IF NOT EXISTS TB_WORKPLACE_WORKER (
    WORKPLACE_WORKER_ID VARCHAR(20) NOT NULL PRIMARY KEY COMMENT '작업장 작업자 ID',
    WORKPLACE_ID VARCHAR(20) NOT NULL COMMENT '작업장 ID',
    WORKER_ID VARCHAR(20) NOT NULL COMMENT '작업자 ID',
    WORKER_NAME VARCHAR(100) NOT NULL COMMENT '작업자명',
    POSITION VARCHAR(50) COMMENT '직책',
    ROLE VARCHAR(20) DEFAULT 'MEMBER' COMMENT '역할 (LEADER/MEMBER)',
    USE_YN CHAR(1) DEFAULT 'Y' COMMENT '사용 여부 (Y/N)',
    REG_USER_ID VARCHAR(20) COMMENT '등록자 ID',
    REG_DT DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
    UPD_USER_ID VARCHAR(20) COMMENT '수정자 ID',
    UPD_DT DATETIME COMMENT '수정일시',
    FOREIGN KEY (WORKPLACE_ID) REFERENCES TB_WORKPLACE(WORKPLACE_ID) ON DELETE CASCADE,
    UNIQUE KEY UK_WORKPLACE_WORKER (WORKPLACE_ID, WORKER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='작업장별 작업자 정보';

-- 작업장별 공정 매핑 테이블
CREATE TABLE IF NOT EXISTS TB_WORKPLACE_PROCESS (
    WORKPLACE_PROCESS_ID VARCHAR(20) NOT NULL PRIMARY KEY COMMENT '작업장 공정 ID',
    WORKPLACE_ID VARCHAR(20) NOT NULL COMMENT '작업장 ID',
    PROCESS_ID VARCHAR(20) NOT NULL COMMENT '공정 ID',
    PROCESS_NAME VARCHAR(100) NOT NULL COMMENT '공정명',
    PROCESS_CODE VARCHAR(50) NOT NULL COMMENT '공정 코드',
    USE_YN CHAR(1) DEFAULT 'Y' COMMENT '사용 여부 (Y/N)',
    REG_USER_ID VARCHAR(20) COMMENT '등록자 ID',
    REG_DT DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
    UPD_USER_ID VARCHAR(20) COMMENT '수정자 ID',
    UPD_DT DATETIME COMMENT '수정일시',
    FOREIGN KEY (WORKPLACE_ID) REFERENCES TB_WORKPLACE(WORKPLACE_ID) ON DELETE CASCADE,
    UNIQUE KEY UK_WORKPLACE_PROCESS (WORKPLACE_ID, PROCESS_ID),
    KEY IX_TB_WORKPLACE_PROCESS_WORKPLACE_ID (WORKPLACE_ID),
    KEY IX_TB_WORKPLACE_PROCESS_PROCESS_ID (PROCESS_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='작업장별 공정 매핑 정보';

-- ID 생성을 위한 테이블 데이터 추가
INSERT INTO IDS (TABLE_NAME, NEXT_ID) VALUES ('TB_WORKPLACE', 1) ON DUPLICATE KEY UPDATE NEXT_ID = NEXT_ID;
INSERT INTO IDS (TABLE_NAME, NEXT_ID) VALUES ('TB_WORKPLACE_WORKER', 1) ON DUPLICATE KEY UPDATE NEXT_ID = NEXT_ID;
INSERT INTO IDS (TABLE_NAME, NEXT_ID) VALUES ('TB_WORKPLACE_PROCESS', 1) ON DUPLICATE KEY UPDATE NEXT_ID = NEXT_ID;
